Repository 100-hours-a-week/4-bull4zo-be, pull requests merged in 2025-05, with the labels that each got.

#26 [Chore] dev 배포 환경 준비 및 테스트용 기능 추가
  src/main/java/com/moa/moa_server/config/DevSecurityConfig.java
  src/main/java/com/moa/moa_server/config/LocalSecurityConfig.java
  src/main/java/com/moa/moa_server/config/ProdSecurityConfig.java
  src/main/java/com/moa/moa_server/config/SecurityConstants.java
  src/main/java/com/moa/moa_server/domain/ai/client/AiModerationClient.java
  src/main/java/com/moa/moa_server/domain/ai/config/AiConfig.java
  src/main/java/com/moa/moa_server/domain/ai/controller/AiController.java
  src/main/java/com/moa/moa_server/domain/ai/dto/ModerationRequest.java
  src/main/java/com/moa/moa_server/domain/ai/dto/ModerationResponse.java
  src/main/java/com/moa/moa_server/domain/ai/mock/MockAiController.java
  src/main/java/com/moa/moa_server/domain/global/controller/TestController.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/java/com/moa/moa_server/config/TestSecurityConfig.java
  src/test/java/com/moa/moa_server/domain/ai/mock/MockAiControllerTest.java
Labels: BE, 개발

#27 [Feat] 프론트-백-AI 서버 간 연동 테스트를 위한 엔드포인트 추가
  src/main/java/com/moa/moa_server/domain/global/controller/TestController.java
Labels: BE, 개발

#39 [Feat] JWT 인증 필터 구현
  src/main/java/com/moa/moa_server/config/LocalSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/JwtAuthenticationFilter.java
  src/main/java/com/moa/moa_server/domain/auth/service/JwtTokenService.java
Labels: BE, 개발

#40 [Feat] 로그아웃 API 구현 및 인증 실패 시 401 응답 처리
  src/main/java/com/moa/moa_server/config/LocalSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/moa/moa_server/config/security/JwtAuthenticationFilter.java
  src/main/java/com/moa/moa_server/domain/auth/controller/AuthController.java
  src/main/java/com/moa/moa_server/domain/auth/repository/TokenRepository.java
  src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java
  src/main/java/com/moa/moa_server/domain/auth/service/RefreshTokenService.java
  src/main/java/com/moa/moa_server/domain/auth/service/impl/RefreshTokenServiceImpl.java
Labels: BE, 개발

#41 [Feat] 투표 도메인 엔티티 및 리포지토리 생성
  src/main/java/com/moa/moa_server/domain/auth/repository/TokenRepository.java
  src/main/java/com/moa/moa_server/domain/group/entity/Group.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java
  src/main/java/com/moa/moa_server/domain/user/entity/User.java
  src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java
  src/main/java/com/moa/moa_server/domain/vote/entity/VoteModerationLog.java
  src/main/java/com/moa/moa_server/domain/vote/entity/VoteResponse.java
  src/main/java/com/moa/moa_server/domain/vote/entity/VoteResult.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteModerationLogRepository.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteResultRepository.java
Labels: BE, 개발

#45 [Feat] 투표 참여 API 개발
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java
  src/main/java/com/moa/moa_server/domain/vote/dto/request/VoteSubmitRequest.java
  src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java
  src/main/java/com/moa/moa_server/domain/vote/entity/VoteResponse.java
  src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: BE, 개발

#46 [Feat] 투표 결과 조회 API 개발
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteOptionResult.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteResultResponse.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: BE, 개발

#48 [Feat] Dev 환경에 Jwt 인증 및 예외 처리 필터 적용
  src/main/java/com/moa/moa_server/config/DevSecurityConfig.java
  src/main/resources/application-dev.yaml
Labels: BE, 개발

#49 [CICD] Dev 서버용 배포 파이프라인
  .github/workflows/cicd-bigbang-dev.yml
Labels: CI/CD

#50 [Feat] 진행 중인 투표 목록 조회 API 개발
  build.gradle
  src/main/java/com/moa/moa_server/config/jpa/JpaAuditingConfig.java
  src/main/java/com/moa/moa_server/config/querydsl/QuerydslConfig.java
  src/main/java/com/moa/moa_server/config/security/DevSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/LocalSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/ProdSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/SecurityConstants.java
  src/main/java/com/moa/moa_server/domain/global/cursor/VoteClosedCursor.java
  src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/list/VoteListItem.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/list/VoteListResponse.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/result/VoteOptionResult.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/result/VoteResultResponse.java
  src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/moa/moa_server/domain/vote/repository/impl/VoteRepositoryImpl.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/resources/application-local.yaml
Labels: BE, 개발

#57 [Feat] 내가 만든 투표 목록 조회 API 개발
  src/main/java/com/moa/moa_server/domain/global/cursor/CreatedAtVoteIdCursor.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/active/ActiveVoteItem.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/active/ActiveVoteResponse.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/list/VoteListResponse.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteResponse.java
  src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/VoteOptionResultWithId.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/moa/moa_server/domain/vote/repository/impl/VoteRepositoryImpl.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteResultService.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: BE, 개발

#59 [Feat] 가입한 그룹 라벨 조회 API 개발
  src/main/java/com/moa/moa_server/domain/global/cursor/GroupNameGroupIdCursor.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepositoryCustom.java
  src/main/java/com/moa/moa_server/domain/group/repository/impl/GroupMemberRepositoryImpl.java
  src/main/java/com/moa/moa_server/domain/user/controller/UserController.java
  src/main/java/com/moa/moa_server/domain/user/dto/response/GroupLabel.java
  src/main/java/com/moa/moa_server/domain/user/dto/response/GroupLabelResponse.java
  src/main/java/com/moa/moa_server/domain/user/handler/UserErrorCode.java
  src/main/java/com/moa/moa_server/domain/user/service/UserService.java
Labels: BE, 개발

#61 [Feat] 그룹 가입 API 개발
  src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java
  src/main/java/com/moa/moa_server/domain/group/dto/request/GroupJoinRequest.java
  src/main/java/com/moa/moa_server/domain/group/dto/response/GroupJoinResponse.java
  src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java
  src/main/java/com/moa/moa_server/domain/group/handler/GroupException.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/group/util/GroupValidator.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: BE, 개발

#62 [Feat] 새 그룹 생성 API 개발
  build.gradle
  src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java
  src/main/java/com/moa/moa_server/domain/group/dto/request/GroupCreateRequest.java
  src/main/java/com/moa/moa_server/domain/group/dto/response/GroupCreateResponse.java
  src/main/java/com/moa/moa_server/domain/group/entity/Group.java
  src/main/java/com/moa/moa_server/domain/group/entity/GroupMember.java
  src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/group/util/GroupValidator.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/java/com/moa/moa_server/domain/vote/util/VoteValidator.java
Labels: BE, 개발

#63 [Feat] 회원정보 조회/수정 API 개발
  src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/user/controller/UserController.java
  src/main/java/com/moa/moa_server/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/moa/moa_server/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/moa/moa_server/domain/user/dto/response/UserUpdateResponse.java
  src/main/java/com/moa/moa_server/domain/user/entity/User.java
  src/main/java/com/moa/moa_server/domain/user/handler/UserErrorCode.java
  src/main/java/com/moa/moa_server/domain/user/repository/UserRepository.java
  src/main/java/com/moa/moa_server/domain/user/service/UserService.java
  src/main/java/com/moa/moa_server/domain/user/util/UserValidator.java
Labels: BE, 개발

#64 [Feat] 회원 탈퇴 API 개발
  src/main/java/com/moa/moa_server/config/RestTemplateConfig.java
  src/main/java/com/moa/moa_server/domain/auth/handler/AuthErrorCode.java
  src/main/java/com/moa/moa_server/domain/auth/repository/OAuthRepository.java
  src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java
  src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java
  src/main/java/com/moa/moa_server/domain/auth/service/strategy/OAuthLoginStrategy.java
  src/main/java/com/moa/moa_server/domain/group/entity/Group.java
  src/main/java/com/moa/moa_server/domain/group/entity/GroupMember.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/user/controller/UserController.java
  src/main/java/com/moa/moa_server/domain/user/entity/User.java
  src/main/java/com/moa/moa_server/domain/user/service/UserService.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: BE, 개발

#65 [Feat] 랜덤 닉네임 생성 기능 구현
  src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java
  src/main/java/com/moa/moa_server/domain/user/handler/UserErrorCode.java
  src/main/java/com/moa/moa_server/domain/user/util/NicknameGenerator.java
  src/main/resources/nickname/adjectives.txt
  src/main/resources/nickname/nouns.txt
Labels: BE, 개발

#67 [Feat] 카카오 로그인 시 동적 redirect URI 허용 및 검증 추가
  src/main/java/com/moa/moa_server/domain/auth/controller/AuthController.java
  src/main/java/com/moa/moa_server/domain/auth/handler/AuthErrorCode.java
  src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java
  src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java
  src/main/java/com/moa/moa_server/domain/auth/service/strategy/OAuthLoginStrategy.java
  src/main/resources/application-dev.yaml
Labels: BE

#70 [Feat] 투표 등록 시 익명 기능 추가
  src/main/java/com/moa/moa_server/domain/vote/dto/response/active/ActiveVoteItem.java
  src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: BE, 개발

#71 [Feat] AI 기반 투표 내용 검열 기능 추가
  src/main/java/com/moa/moa_server/domain/ai/controller/AiController.java
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteModerationController.java
  src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationCallbackRequest.java
  src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationCallbackResponse.java
  src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationRequest.java
  src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java
  src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteModerationService.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/resources/application-local.yaml
Labels: BE, 개발

#78 [Feat] 사용자 피드백 등록 API 개발
  src/main/java/com/moa/moa_server/domain/feedback/controller/FeedbackController.java
  src/main/java/com/moa/moa_server/domain/feedback/dto/request/FeedbackCreateRequest.java
  src/main/java/com/moa/moa_server/domain/feedback/entity/Feedback.java
  src/main/java/com/moa/moa_server/domain/feedback/handler/FeedbackErrorCode.java
  src/main/java/com/moa/moa_server/domain/feedback/handler/FeedbackException.java
  src/main/java/com/moa/moa_server/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/moa/moa_server/domain/feedback/service/FeedbackService.java
  src/main/java/com/moa/moa_server/domain/feedback/util/FeedbackValidator.java
Labels: BE, 개발

#80 [Fix] 투표 종료 시각 UTC 저장 및 로컬 환경 처리 개선
  src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/java/com/moa/moa_server/domain/vote/util/VoteValidator.java
Labels: 버그-일반, BE

#82 [Fix] 투표 상태 응답을 종료 시각 기반으로 계산하도록 수정
  src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java
Labels: 버그-일반, BE

#83 [Fix] #81 병합 후 REJECTED, PENDING 상태 반영 누락 수정
  src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java
Labels: 버그-일반, BE

#84 [Fix] Vote 종료 시각 UTC 저장 누락 수정
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
Labels: 버그-일반, BE

#115 feat: lucy-xss-filter 기반 XSS 필터링 적용
  build.gradle
  src/main/java/com/moa/moa_server/domain/global/util/XssUtil.java
  src/main/java/com/moa/moa_server/domain/group/service/GroupService.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/resources/lucy-xss-superset.xml
Labels: BE, 개발

#119 chore: checkstyle 검사에서 QueryDSL Q클래스 제외
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: BE

#127 feat: 테스트용 로그인 API 및 더미 데이터 삽입 SQL 스크립트 추가
  db/README.md
  db/testdata/init_users.sql
  db/testdata/init_vote_responses.sql
  db/testdata/init_votes.sql
  db/testdata/truncate_all.sql
  src/main/java/com/moa/moa_server/config/security/SecurityConstants.java
  src/main/java/com/moa/moa_server/domain/test/controller/TestLoginController.java
Labels: BE

#130 feat: 집계 테이블 기반 투표 API(V2) 및 목록 조회 API 구현
  db/README.md
  db/testdata/init_vote_responses.sql
  db/testdata/init_vote_results.sql
  db/testdata/truncate_all.sql
  src/main/java/com/moa/moa_server/config/security/LocalSecurityConfig.java
  src/main/java/com/moa/moa_server/config/security/SecurityConstants.java
  src/main/java/com/moa/moa_server/domain/global/handler/GlobalExceptionHandler.java
  src/main/java/com/moa/moa_server/domain/test/controller/TestLoginController.java
  src/main/java/com/moa/moa_server/domain/vote/controller/VoteControllerV2.java
  src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java
  src/main/java/com/moa/moa_server/domain/vote/repository/VoteResultRepository.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
  src/main/java/com/moa/moa_server/domain/vote/service/VoteServiceV2.java
  src/main/resources/application-local.yaml
Labels: BE, 개발

#148 chore: hotfix(v1.3.1) 반영 (XSS 필터링 예외 처리)
  src/main/java/com/moa/moa_server/domain/global/cursor/ClosedAtVoteIdCursor.java
  src/main/java/com/moa/moa_server/domain/global/util/XssUtil.java
  src/main/resources/application-prod.yaml
  src/main/resources/lucy-xss-superset.xml
  src/test/java/com/moa/moa_server/domain/global/util/XssUtilTest.java
Labels: BE
